#!/bin/bash

function up {
    zig build run -- $(pwd)/test_data/gemini-root 1965 ./dummy-certs/dummy.crt ./dummy-certs/dummy.key
}

function watch {
    zig build --watch
}

function debug {
    lldb zig-out/bin/gemini-server-zig -- $(pwd)/test_data/gemini-root 1965 ./dummy-certs/dummy.crt ./dummy-certs/dummy.key
}

function test {
    zig build test
}

function thirdparty-test-suite {
    ~/ThirdParty/gemini-diagnostics/gemini-diagnostics
}

function release-fast {
    zig build --release=fast
}

function deploy {
    # use gemini-php folder for now.
    # it's where my current blog is
    scp zig-out/bin/gemini-server-zig vpn-droplet:/home/gemini/gemini-php
}

# This function runs the gemini-diagnostics script from
# https://github.com/michael-lazar/gemini-diagnostics.git
#
# It assumes that this repo is available in the root folder of this project.
#
# The purpose of this function is to ignore a few particular errors I don't plan fixing atm.
function run-diagnostic {
    echo "" > diagnostics.output
    ./gemini-diagnostics/gemini-diagnostics > diagnostics.output
    cat diagnostics.output # just so we can see the whole result it in CI
    cat diagnostics.output | grep "Failed 2 checks: TLSClaims, URLWrongHost"
}

function default {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-default}
