#!/bin/bash

function up {
    zig build run -- $(pwd)/test_data/gemini-root 1965 certificate.crt private.key
}

function watch {
    zig build --watch
}

function debug {
    lldb zig-out/bin/gemini-server-zig -- $(pwd)/test_data/gemini-root 1965 certificate.crt private.key
}

function test {
    zig build test
}

function thirdparty-test-suite {
    ~/ThirdParty/gemini-diagnostics/gemini-diagnostics
}

function release-fast {
    zig build --release=fast
}

function deploy {
    # use gemini-php folder for now.
    # it's where my current blog is
    scp zig-out/bin/gemini-server-zig vpn-droplet:/home/gemini/gemini-php
}

function default {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-default}
